name: encacap-re-acbuilding

services:
  itn-ere-fe-web-app-prod-a:
    container_name: itn-ere-fe-web-app-prod-a
    image: hiencacap/itn-ere-fe-web-app:prod-a
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      platforms:
        - linux/amd64
    command: ["yarn", "run", "start", "--port", "20200"]
    ports:
      - 20200:20200
    env_file:
      - .env.production
    environment:
      - NEXT_PUBLIC_RE_ACB_API_URL=http://itn-ere-bff-web-prod-a:20100
    networks:
      - itn-ere-network

networks:
  itn-ere-network:
    external: true
    driver: bridge
